import music from "../../public/fakeCatsImages/music.jpg";
import clothes from "../../public/fakeCatsImages/clothes.jpg";
import livreBatuque from "../../public/fakeApi/livreBatuque.jpg";
import livreBatuqueBack from "../../public/fakeApi/livreBatuqueBack.jpg";
import livreBatuqueOpen from "../../public/fakeApi/livreBatuqueOpen.jpg";
import livretexpressao from "../../public/fakeApi/livretexpressao.jpg";

export const products = [
  {
    subCategory: "berimbau Viola",
    products: [
      {
        name: "berimbau Viola par Mestre Foguete",
        price: 60,
        rates: [
          { authId: "", rate: 3 },
          { authId: "", rate: 4 },
          { authId: "", rate: 5 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
        ],
        availability: "now",
        id: "123454",
        date: new Date(),
        isBestSeller: true,
        linkedProducts: ["id1", "id2", "id3"],
        specs: ["", "", "", "", ""],
        variants: [{ alt: "", image: "", id: "" }],
        images: [
          { image: music, alt: "" },
          { image: music, alt: "" },
          { image: music, alt: "" },
        ],
        comments: [
          {
            title: "YEah",
            authorName: "goku",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Il sonne trop bien",
          },
          {
            title: "YEah",
            authorName: "Pernalonga",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Je n'arrive pas à l'accorder, comment faire ?",
          },
          {
            title: "YEah",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Cool, est-ce qu'il y a aussi des medios ?",
          },
        ],
      },
      {
        name: "berimbau Gunga fabriqué au Brésil",
        price: 59.99,
        rates: [
          { authId: "", rate: 3 },
          { authId: "", rate: 4 },
          { authId: "", rate: 0 },
          { authId: "", rate: 2 },
          { authId: "", rate: 1 },
          { authId: "", rate: 1 },
          { authId: "", rate: 4 },
        ],
        availability: "now",
        id: "321454",
        date: new Date(),
        isBestSeller: false,
        linkedProducts: ["id1", "id2", "id3"],
        specs: ["", "", "", "", ""],
        variants: [{ alt: "", image: "", id: "" }],
        images: [
          { image: music, alt: "" },
          { image: music, alt: "" },
        ],
        comments: [
          {
            title: "YEah",
            authorName: "Laïa",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Il sonne vraiment bien",
          },
          {
            title: "YEah",
            authorName: "Pixote",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "E bom !",
          },
          {
            title: "YEah",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Cool, est-ce qu'il y a aussi des medios ?",
          },
        ],
      },
      {
        name: "berimbau Viola fait avec du bois de Noisetié",
        price: 29.9,
        rates: [
          { authId: "", rate: 3 },
          { authId: "", rate: 4 },
          { authId: "", rate: 5 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
        ],
        availability: "command",
        id: "12344409876",
        date: new Date(),
        isBestSeller: false,
        linkedProducts: ["id1", "id2", "id3"],
        specs: ["", "", "", "", ""],
        variants: [{ alt: "", image: "", id: "" }],
        images: [
          { image: music, alt: "" },
          { image: music, alt: "" },
        ],
        comments: [
          {
            title: "YEah",
            authorName: "Chama",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Super rapport qualité prix",
          },
          {
            title: "YEah",
            authorName: "Babalo",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "J'aime pas'",
          },
          {
            title: "YEah",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Cool, est-ce qu'il y a aussi des medios ?",
          },
        ],
      },
    ],
  },
  {
    subCategory: "chaussures",
    products: [
      {
        name: "Chaussure Capoeira - Rainha VL2500 - Bleu-gris",
        price: 57.79,
        rates: [
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
          { authId: "", rate: 3 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
        ],
        availability: "now",
        id: "12345456789",
        date: new Date(),
        isBestSeller: true,
        linkedProducts: ["id1", "id2", "id3"],
        specs: [
          "Marque Rainha Volei VL 2500",
          "SEMELLE INTÉRIEURE Textile",
          "SEMELLE Caoutchouc latex avec nervures antidérapantes",
          "MATÉRIAU SUPÉRIEUR en Toile 100 % coton",
          "interne en Textile",
        ],
        variants: [
          { alt: "", image: clothes, id: "111111111" },
          { alt: "", image: clothes, id: "222222222" },
          { alt: "", image: clothes, id: "333333333" },
          { alt: "", image: clothes, id: "12345456789" },
        ],
        images: [
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
          {
            alt: "",
            image: clothes,
          },
          {
            alt: "",
            image: music,
          },
        ],
        comments: [
          {
            title: "YEah",
            authorName: "goku",
            authorId: "",
            date: new Date(),
            rating: 4,
            comment: "Il sonne trop bien",
          },
          {
            title: "J'aime",
            authorName: "Pernalonga",
            authorId: "",
            date: new Date(),
            rating: 5,
            comment: "Top à l'aise",
          },
          {
            title: "Ok à première vue",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Ca a l'air solide on verra avec le temps",
          },
        ],
      },
      {
        name: "Chaussure Capoeira - Rainha VL2500 -Blanc-bleu ",
        price: 57.69,
        rates: [
          { authId: "", rate: 2 },
          { authId: "", rate: 2 },
          { authId: "", rate: 2 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
        ],
        availability: "nostock",
        id: "111111111",
        date: new Date(),
        isBestSeller: false,
        linkedProducts: ["id1", "id2", "id3"],
        specs: ["", "", "", "", ""],
        variants: [
          { alt: "", image: clothes, id: "222222222" },
          { alt: "", image: clothes, id: "333333333" },
          { alt: "", image: clothes, id: "12345456789" },
          { alt: "", image: clothes, id: "111111111" },
        ],
        images: [{ image: clothes, alt: "" }],
        comments: [
          {
            title: "Bien",
            authorName: "Laïa",
            authorId: "",
            date: new Date(),
            rating: 4,
            comment: "Bien bien",
          },
          {
            title: "Khaja",
            authorName: "Pixote",
            authorId: "",
            date: new Date(),
            rating: 2.5,
            comment: "Le top !",
          },
          {
            title: "Top !",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Elles sont moins chères au Brésil nan ?",
          },
        ],
      },
      {
        name: "Chaussure Capoeira - Rainha VL2500 -Blanc-noir",

        price: 59.6,
        rates: [
          { authId: "", rate: 3 },
          { authId: "", rate: 5 },
          { authId: "", rate: 3 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 3 },
        ],

        availability: "nostock",
        id: "222222222",
        date: new Date(),
        isBestSeller: true,
        linkedProducts: ["id1", "id2", "id3"],
        specs: ["", "", "", "", ""],
        variants: [
          { alt: "", image: clothes, id: "111111111" },
          { alt: "", image: clothes, id: "222222222" },
          { alt: "", image: clothes, id: "333333333" },
          { alt: "", image: clothes, id: "12345456789" },
        ],
        images: [{ image: clothes, alt: "" }],
        comments: [
          {
            title: "YEah",
            authorName: "Laïa",
            authorId: "",
            date: new Date(),
            rating: 4,
            comment: "Bien bien",
          },
          {
            title: "ouds",
            authorName: "Pixote",
            authorId: "",
            date: new Date(),
            rating: 2,
            comment: "Au top !",
          },
          {
            title: "Super",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Elles sont moins chères au Brésil nan ?",
          },
        ],
      },
      {
        name: "Chaussure Capoeira - Rainha VL2500 -Blanc-rouge",

        price: 55,
        rates: [
          { authId: "", rate: 3 },
          { authId: "", rate: 4 },
          { authId: "", rate: 5 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
        ],
        availability: "command",
        id: "333333333",
        date: new Date(),
        isBestSeller: false,
        linkedProducts: ["id1", "id2", "id3"],
        specs: ["", "", "", "", ""],
        variants: [
          { alt: "", image: clothes, id: "111111111" },
          { alt: "", image: clothes, id: "222222222" },
          { alt: "", image: clothes, id: "333333333" },
          { alt: "", image: clothes, id: "12345456789" },
        ],
        images: [
          {
            image: clothes,
            alt: "",
          },
        ],
        comments: [
          {
            title: "YEah",
            authorName: "Laïa",
            authorId: "",
            date: new Date(),
            rating: 4,
            comment: "Bien bien",
          },
          {
            title: "J'adore !",
            authorName: "Pixote",
            authorId: "",
            date: new Date(),
            rating: 2,
            comment: "Au top !",
          },
          {
            title: "Cool",
            authorNameName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Elles sont moins chères au Brésil nan ?",
          },
        ],
      },
    ],
  },
  {
    subCategory: "livre",
    products: [
      {
        name: "LIVRET EXPRESSÃO DA ARTE MAI-JUIN 2003",
        price: 12.92,
        rates: [
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
          { authId: "", rate: 4 },
          { authId: "", rate: 4 },
          { authId: "", rate: 4 },
          { authId: "", rate: 4 },
          { authId: "", rate: 4 },
        ],
        availability: "now",
        id: "987654321",
        date: new Date(),
        isBestSeller: true,
        linkedProducts: ["id1", "id2", "id3"],
        specs: [
          "En portugais",
          "30 pages",
          "au format de poche (voir photo)",
          "MATÉRIAU SUPÉRIEUR en Toile 100 % coton",
          "interne en Textile",
        ],
        variants: [],
        images: [
          {
            alt: "",
            image: livretexpressao,
          },
          {
            alt: "",
            image: livretexpressao,
          },
        ],
        comments: [
          {
            title: "YEah",
            authorName: "goku",
            authorId: "",
            date: new Date(),
            rating: 4,
            comment: "Il sonne trop bien",
          },
          {
            title: "J'aime",
            authorName: "Pernalonga",
            authorId: "",
            date: new Date(),
            rating: 5,
            comment: "Top à l'aise",
          },
          {
            title: "Ok à première vue",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Ca a l'air solide on verra avec le temps",
          },
        ],
      },
      {
        name: "Livre O Batuque, a luta braba (Frede Abreu)",
        price: 100.32,
        rates: [
          { authId: "", rate: 2 },
          { authId: "", rate: 2 },
          { authId: "", rate: 2 },
          { authId: "", rate: 2 },
          { authId: "", rate: 5 },
          { authId: "", rate: 4 },
        ],
        availability: "nostock",
        id: "112233445",
        date: new Date(),
        isBestSeller: false,
        linkedProducts: ["id1", "id2", "id3"],
        specs: [
          "Bilingue (portugais et anglais)",
          "152 pages",
          "Par Frede Abreu, chercheur et historien passioné par l'histoire de la capoeira",
          "Livre rare (édition cloturée)",
          "Edition limitée",
        ],
        variants: [],
        images: [
          { image: livreBatuque, alt: "" },
          { image: livreBatuqueBack, alt: "" },
          { image: livreBatuqueOpen, alt: "" },
        ],
        comments: [
          {
            title: "Bien",
            authorName: "Laïa",
            authorId: "",
            date: new Date(),
            rating: 4,
            comment: "Bien bien",
          },
          {
            title: "Khaja",
            authorName: "Pixote",
            authorId: "",
            date: new Date(),
            rating: 2.5,
            comment: "Le top !",
          },
          {
            title: "Top !",
            authorName: "Tanjiro",
            authorId: "",
            date: new Date(),
            rating: 3,
            comment: "Elles sont moins chères au Brésil nan ?",
          },
        ],
      },
    ],
  },
];
